import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import EmployeeProfile, { Departments, Status } from 'App/Models/EmployeeProfileTable'
import moment from 'moment'

export default class EmployeeProfileSeeder extends BaseSeeder {
  public async run () {
    // Write your database queries inside the run method
    await EmployeeProfile.createMany([
      {
        first_name: 'Angelo',
        last_name: 'Palma',
        birthdate: moment('10-1-1998','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Single',
        department: Departments.Engineering,
        position: 'Janitor',
        date_hired: moment('7-5-2021','DD-MM-YYYY').toDate(),
        employment_status: Status.Probitionary,
        contact_number: '639814261784',
        email: 'janitor@janitors.com',
        address: 'Dapita, Cordova, Cebu Province, 6015',
        city: 'Cebu City',
        province: 'Cebu',
        nationality: 'Filipino',
      },
      {
        first_name: 'Vince',
        last_name: 'Quinaging',
        birthdate: moment('15-10-1999','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Single',
        department: Departments.Engineering,
        position: 'TL',
        date_hired: moment('7-5-2021','DD-MM-YYYY').toDate(),
        employment_status: Status.Probitionary,
        contact_number: '639321458791',
        email: 'tlvince@teamlead.com',
        address: 'Camolinas, Cordova, Cebu Province, 6015',
        city: 'Cebu City',
        province: 'Cebu',
        nationality: 'Filipino',
      },
      {
        first_name: 'Aljune',
        last_name: 'Degamo',
        birthdate: moment('12-2-1969','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Single',
        department: Departments.Engineering,
        position: 'sub TL',
        date_hired: moment('7-5-2021','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639631548216',
        email: 'subtlaljune@subteamlead.com',
        address: 'Camolinas, Cordova, Cebu Province, 6015',
        city: 'Cebu City',
        province: 'Cebu',
        nationality: 'Filipino',
      },
      {
        first_name: 'Ryan',
        last_name: 'Canseco',
        birthdate: moment('1-23-1996','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Single',
        department: Departments.Engineering,
        position: 'Manager',
        date_hired: moment('1-5-2022','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '6393148576983',
        email: 'managerryan@manager.com',
        address: 'Brgy. Matumbo, Pusok,Lapu-Lapu City, Cebu, 6015',
        city: 'Lapu-Lapu City',
        province: 'Cebu',
        nationality: 'Filipino',
      },
      {
        first_name: 'Anne',
        last_name: 'Marie',
        birthdate: moment('5-30-1991','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Singer/Composer',
        date_hired: moment('1-5-2010','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '63914264891',
        email: 'singeranne@singer.com',
        address: 'Los Angeles, California, USA',
        city: 'California',
        province: 'California',
        nationality: 'American',
      },
      {
        first_name: 'Kobe',
        last_name: 'Bryant',
        birthdate: moment('8-23-1978','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Basketball Legend',
        date_hired: moment('3-5-1996','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639647813499',
        email: 'kobebryant@nba.com',
        address: 'Los Angeles, California, USA',
        city: 'California',
        province: 'California',
        nationality: 'American',
      },
      {
        first_name: 'Michael',
        last_name: 'Jackson',
        birthdate: moment('8-29-1958','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Singer Legend',
        date_hired: moment('9-15-1970','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639128649710',
        email: 'michaelbjackson@hollywood.com',
        address: 'Los Angeles, California, USA',
        city: 'California',
        province: 'California',
        nationality: 'American',
      },
      {
        first_name: 'Michael',
        last_name: 'Vitoy',
        birthdate: moment('12-17-1969','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Maried',
        department: Departments.Admin,
        position: 'Artist',
        date_hired: moment('11-19-1990','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639331245622',
        email: 'michaelv@gma.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Marian',
        last_name: 'Rivera',
        birthdate: moment('8-18-1984','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Married',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('11-19-1990','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639145782164',
        email: 'marianriver@gma.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Dingdong',
        last_name: 'Dantes',
        birthdate: moment('8-2-1980','DD-MM-YYYY').toDate(),
        gender:'Male',
        marital_status: 'Married',
        department: Departments.Engineering,
        position: 'Artist',
        date_hired: moment('4-20-1998','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639145782164',
        email: 'dingdongdantes@gma.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Nadine',
        last_name: 'Lustre',
        birthdate: moment('31-10-1993','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('2-28-2010','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639215648917',
        email: 'nadinelustre@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Sue',
        last_name: 'Ramirez',
        birthdate: moment('20-07-1996','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Artist',
        date_hired: moment('30-01-2011','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639335648918',
        email: 'sueramirez@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Julie Ann',
        last_name: 'San Jose',
        birthdate: moment('17-05-1994','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Artist',
        date_hired: moment('27-06-2008','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639336124855',
        email: 'julieann@localartist.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Kathryn',
        last_name: 'Bernardo',
        birthdate: moment('26-03-1996','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Artist',
        date_hired: moment('22-05-2008','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639315469784',
        email: 'kathb@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Maja',
        last_name: 'Salvador',
        birthdate: moment('5-10-1988','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Artist',
        date_hired: moment('24-8-2000','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639648514793',
        email: 'majas@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Maris',
        last_name: 'Racal',
        birthdate: moment('22-9-1997','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Admin,
        position: 'Artist',
        date_hired: moment('7-11-2012','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639785462151',
        email: 'marisr@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Julia',
        last_name: 'Barreto',
        birthdate: moment('10-03-1997','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('7-11-2012','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639885467895',
        email: 'juliab@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Ylona',
        last_name: 'Garcia',
        birthdate: moment('28-2-2002','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('29-5-2019','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639786419513',
        email: 'ylonag@abs-cbn.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Ivana',
        last_name: 'Alawi',
        birthdate: moment('25-12-1994','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('28-09-2017','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639786419513',
        email: 'ivanaa@vlogger.com',
        address: 'manila, Philippines',
        city: 'Manila',
        province: 'Manila',
        nationality: 'Filipino',
      },
      {
        first_name: 'Jennifer',
        last_name: 'Lawrence',
        birthdate: moment('15-8-1990','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('27-12-2005','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '639875618941',
        email: 'jlaw@hollywoodceleb.com',
        address: 'Indian Hills, Kentucky, United States',
        city: 'Kentucky',
        province: 'Kentucky',
        nationality: 'American',
      },
      {
        first_name: 'Emma',
        last_name: 'Watson',
        birthdate: moment('15-4-1990','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('21-11-2001','DD-MM-YYYY').toDate(),
        employment_status: Status.Regular,
        contact_number: '63986412549',
        email: 'emmaw@hollywoodceleb.com',
        address: 'Paris, France',
        city: 'France',
        province: 'France',
        nationality: 'American',
      },
      {
        first_name: 'Vanessa',
        last_name: 'Hudgens',
        birthdate: moment('14-12-1988','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('3-10-2019','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '639846214578',
        email: 'vanessah@hollywoodceleb.com',
        address: 'Salinas, California, United States',
        city: 'California',
        province: 'California',
        nationality: 'American',
      },
      {
        first_name: 'Amanda',
        last_name: 'Seyfried',
        birthdate: moment('3-12-1985','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('23-1-2000','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '63933578491',
        email: 'arianag@hollywoodceleb.com',
        address: 'Allentown, Pennsylvania, United States',
        city: 'Pennsylvania',
        province: 'Pennsylvania',
        nationality: 'American',
      },
      {
        first_name: 'Amanda',
        last_name: 'Seyfried',
        birthdate: moment('03-12-1985','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('23-01-2000','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '63933578491',
        email: 'amandas@hollywoodceleb.com',
        address: 'Allentown, Pennsylvania, United States',
        city: 'Pennsylvania',
        province: 'Pennsylvania',
        nationality: 'American',
      },
      {
        first_name: 'Ariana',
        last_name: 'Grande',
        birthdate: moment('26-06-1993','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('29-08-2010','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '63933578491',
        email: 'arianag@hollywoodceleb.com',
        address: 'Boca Raton, Florida, United States',
        city: 'Florida',
        province: 'Florida',
        nationality: 'American',
      },
      {
        first_name: 'Emma',
        last_name: 'Stone',
        birthdate: moment('06-11-1988','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Artist',
        date_hired: moment('20-04-2005','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '63933578491',
        email: 'emmas@hollywoodceleb.com',
        address: 'Scottsdale, Arizona, United States',
        city: 'Arizona',
        province: 'Arizona',
        nationality: 'American',
      },
      {
        first_name: 'Selena',
        last_name: 'Gomez',
        birthdate: moment('22-07-1992','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Actres/Singer',
        date_hired: moment('01-01-2006','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '639864895613',
        email: 'selenag@hollywoodceleb.com',
        address: ' Grand Prairie, Texas, United States',
        city: 'Texas',
        province: 'Texas',
        nationality: 'American',
      },
      {
        first_name: 'Anne',
        last_name: 'Hathaway',
        birthdate: moment('12-11-1982','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'Actres/Singer',
        date_hired: moment('30-02-2003','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '639864895613',
        email: 'anneh@hollywoodceleb.com',
        address: 'Brooklyn, New York, United States',
        city: 'New York',
        province: 'New York',
        nationality: 'American',
      },
      {
        first_name: 'Taylor',
        last_name: 'Swift',
        birthdate: moment('13-12-1989','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'American singer',
        date_hired: moment('24-08-2006','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '639847569814',
        email: 'taylors@hollywoodceleb.com',
        address: ' West Reading, Pennsylvania, United States',
        city: 'Pennsylvania',
        province: 'Pennsylvania',
        nationality: 'American',
      },
      {
        first_name: 'Megan',
        last_name: 'Fox',
        birthdate: moment('16-05-1986','DD-MM-YYYY').toDate(),
        gender:'Female',
        marital_status: 'Single',
        department: Departments.Finance,
        position: 'American singer',
        date_hired: moment('24-08-2006','DD-MM-YYYY').toDate(),
        employment_status: Status.Casual,
        contact_number: '639847569814',
        email: 'taylors@hollywoodceleb.com',
        address: ' West Reading, Pennsylvania, United States',
        city: 'Pennsylvania',
        province: 'Pennsylvania',
        nationality: 'American',
      },
    ])
  }
}
